### ISSUE TITLE
EnTK on Princeton cluster

### ISSUE THREAD

**Issue by uvaaland** [radical-collaboration/hpc-workflows#82] opened 2019-02-04 18:19 UTC
@jeroentromp expressed interest in setting up the pilot + EnTK on one of the Princeton clusters to have a local testing ground for us to try things out before taking them to Summit.

Princeton will be getting a couple of Summit nodes in the near future, which might make the setup easier.

**Comment by vivek-bala** [comment] 2019-02-05 15:24
Hey @uvaaland , can you add any links to the user guide or documentation for the Princeton cluster. That will be helpful in planning.

**Comment by uvaaland** [comment] 2019-02-05 15:53
The relevant cluster right now is the TigerGPU cluster:
https://researchcomputing.princeton.edu/systems-and-services/available-systems/tiger

The Summit nodes will make up their own cluster. That is, it will be a mini-Summit and so the setup should be similar to what had to be done for Summit itself.

**Comment by vivek-bala** [comment] 2019-02-13 15:42
Both Andre and I have got an account on the Tiger cluster. Thanks Uno and Jeroen!

**Comment by andre-merzky** [comment] 2019-03-06 21:35
So I know my netid for princeton (but I don't think I have seen nor set a password anywhere).

Next step, according to the [docs](https://researchcomputing.princeton.edu/getting-started/how-use-our-systems) I could find, would be to enable shell access.  The [respective page](https://princeton.service-now.com/snap?id=kb_article&sys_id=822a27064f9ca20018ddd48e5210c743) says:

```
New Unix accounts (Undergraduate accounts excepted) will be set up with a default Unix shell of /bin/nologin that prohibits login access. If you wish to use a your Unix account, simply change this option by using the Enable Unix Account page.  Note: The Enable Unix Account page is only accessible from the Princeton Campus Network, not off-campus.
```

Any idea how to handle this, and/or whom to contact for some hand holding?

**Comment by uvaaland** [comment] 2019-03-11 15:53
Hi, Andre!

It was my understanding from talking to Vivek that he was able to log in and do what needs to be done. Maybe @vivek-bala can clarify if we are missing a step?

**Comment by andre-merzky** [comment] 2019-03-21 21:45
Hey @uvaaland , I think I would benefit from your support.  I got my netid - but all the ways to access the machine require some initial password.  I never set such an initial password anywhere, and don't see any notification with an initial password.

The form  (second page after entering the netid) [points](https://puaccess.princeton.edu/) to `609-258-HELP` as support contact for lost passwords - but that does not really look like a phone number?  Can you interpret that number?   Any advise on how I can obtain that password?

Thanks!

**Comment by uvaaland** [comment] 2019-03-21 22:26
Hi, Andre!

Yes, let's look at this together tomorrow. I will be at the office by 0930 EST and am free to connect with you anytime outside 1100-1130, when I have a meeting. Let me know if you can work with that, and I am confident that we should be able to work through this without too much effort :)

Uno
________________________________

**Comment by andre-merzky** [comment] 2019-03-21 22:28
I find it fascinating how much the process of getting access to some machine resembles an old-school  role playing game: heroic quests, discovering new pages, talking to different RPC, false leads, some light lies (yes, this is my campus address...), lots of note taking and mapping...

Long story short, I got access now - thanks to @vivek-bala for some crucial cheat codes! :-D

**Comment by uvaaland** [comment] 2019-03-22 13:39
Haha, how exciting! I am happy to hear that it worked out. And don't hesitate to reach out if there is anything else you should need :)

Uno
________________________________

**Comment by andre-merzky** [comment] 2019-04-03 18:40
A basic setup is now functional on `tiger_cpu`.  I still need to test MPI tasks and GPU support, but from what I can see this should work (tests are in the queue).

Using RCT on `tiger_[cg]pu` requires a manual configuration step - the pilot is not able to bootstrap itself on the compute nodes due to DNS setup issues.  We may be able to work around this eventually, for now the user needs to run two commands to prepare the stack.

I will need to do some  more testing, but in general I would assume that we can release this toward the end of the week - the code changes in RCT is minuscule (some fixes to rarely used code paths), its basically just adding the config entries.

Please let me know if you have a specific application I should test.

**Comment by andre-merzky** [comment] 2019-04-03 19:01
Uh, MPI still fails.  Do you happen to have a recommendation on what modules to load for MPI  setup?

**Comment by uvaaland** [comment] 2019-04-03 19:03
The one that I am currently using for my runs is:

module load openmpi/intel-17.0/2.1.0/64

**Comment by andre-merzky** [comment] 2019-04-03 19:23
> openmpi/intel-17.0/2.1.0/64

great, let me try that one...

**Comment by andre-merzky** [comment] 2019-04-03 19:43
@uvaaland advised to load the intel compiler module first, that resolved the mpirun problem.  We are up and running now.  Some more tests are needed with the actual workload, and I want to look into some bootstrapping delays - but it looks we are on track to releasing this soon.

**Comment by andre-merzky** [comment] 2019-04-17 11:08
PR for RP: https://github.com/radical-cybertools/radical.pilot/pull/1852

Note that of today I see network problems on tiger_cpu (unrelated to RP).

**Comment by andre-merzky** [comment] 2019-04-17 11:12
for the record on the network issues mentioned above:

```
(ve)  tigercpu  amerzky  ~/radical/radical.pilot  [feature/tiger *] $ ping github.com
PING github.com (192.30.253.112) 56(84) bytes of data.
^C
--- github.com ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 3999ms

(ve)  tigercpu  amerzky  ~/radical/radical.pilot  1  [feature/tiger *] $ host github.com
github.com has address 192.30.253.112
github.com has address 192.30.253.113
github.com mail is handled by 5 ALT2.ASPMX.L.GOOGLE.com.
github.com mail is handled by 10 ALT4.ASPMX.L.GOOGLE.com.
github.com mail is handled by 1 ASPMX.L.GOOGLE.com.
github.com mail is handled by 5 ALT1.ASPMX.L.GOOGLE.com.
github.com mail is handled by 10 ALT3.ASPMX.L.GOOGLE.com.

(ve)  tigercpu  amerzky  ~/radical/radical.pilot  [feature/tiger *] $ ping github.com
PING github.com (192.30.253.113) 56(84) bytes of data.
64 bytes from lb-192-30-253-113-iad.github.com (192.30.253.113): icmp_seq=1 ttl=51 time=7.51 ms
64 bytes from lb-192-30-253-113-iad.github.com (192.30.253.113): icmp_seq=2 ttl=51 time=7.42 ms
^C
--- github.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 7.425/7.472/7.519/0.047 ms
```

It seems like the DNS resolver fails, but it's cache can be repopulated by manual resolving via `host` lookup.  That cache times out after some seconds.  I did not attempt to work around this in the RP pilot bootstrapper, but it seems to stumble over this very problem.

**Comment by mturilli** [comment] 2019-04-17 19:14
- Open a ticket with support
- Princeton made available a real-life use-case script for testing
- Confirm support and release.

**Comment by andre-merzky** [comment] 2019-04-17 19:15
use case: `/scratch/gpfs/uvaaland/research/radical_collaboration/specfem3d_globe`

**Comment by uvaaland** [comment] 2019-04-17 19:17
To open a ticket with PU system administrators regarding cluster usage, send an email to cses@princeton.edu. They are usually quick to respond.

**Comment by andre-merzky** [comment] 2019-04-29 08:03
Hi @uvaaland, 

I encounter troubles  with OpenMPI (mpirun segfaults), but seem to have success with intel-mpi.  The following modules seem to result in a sane setup:

```
module purge
module load intel
module load intel-mpi
module load intel-python/2.7
```

Your application is linked against OpenMPI.  I don't seem to have enough disk quota to clone the specfm repo and to recompile with intel-mpi to check if that's viable - do you know if that works?  If not, would you mind giving it a try?  Meanwhile I will continue to look into OpenMPI.

The `feature/tiger` branch now should work on `tiger`.  It is possible to submit to both the `cpu` and the `gpu` queue, and our tests succeed.  

Tiger has some connectivity constraints which we didn't see in a while, so I had to refresh/fix some tunneling code, but that is in place now.  To give it a try, you would need to (after loading the modules above):

```
$ git clone git@github.com:radical-cybertools/radical.pilot.git
$ cd radical.pilot
$ git checkout feature/tiger
$ ./bin/radical-pilot-ve ve
$ source ve/bin/activate
(ve) $ pip install .
(ve) $ ./bin/radical-pilot-create-static-ve ~/radical.pilot.sandbox/ve.princeton.tiger/
(ve) $ ./examples/09_mpi_units.py princeton.tiger_cpu
(ve) $ ./examples/09_mpi_units.py princeton.tiger_gpu
```

If you find the opportunity to try that, would you let me know if that results in successful runs of the examples?

Thanks!

**Comment by uvaaland** [comment] 2019-04-29 13:20
Hi, Andre!

I have tried the above commands and can confirm that both examples are working for me. The only additional step I needed to take in order for it to work was:

export RADICAL_PILOT_DBURL="mongodb://user:user123@ds043012.mlab.com:43012/princeton"

If you are having issues with the quota, use the command `checkquota` which will list the storage you have available. My suspicion is that you are working in `/home/amerzky/` which has only 10-20GB. But you should have storage on `/scratch/gpfs/amerzky/` and/or `/tigress/amerzky/` which has 500GB each. I strongly recommend you work in one of the latter two folders.

**Comment by andre-merzky** [comment] 2019-04-30 07:47
@uvaaland : Ah, since `$HOME` was shared, I did not even consider looking for other FS...  Duh!  Will do.

**Comment by andre-merzky** [comment] 2019-04-30 07:53
We hit a SNAFU on tiger, in that the available OpenMPI modules seem to be unreliable.  Specifically their `mpirun` seems to segfault now and then, which makes task placement in RP unstable.

We have two immediate options: (a) recompile the application against `intel-mpi` (intel-mpi is based on MPICH, and the launcher seems stable AFAICT), (b) implement an `srun` base launch method for RP.  The second is not too difficult, but somewhat cumbersome as `srun` needs us to trick it into placing tasks correctly (by modifying env settings per invocation).  

I think there is something to be gained from both options, since we want to use the stack (both application and RCT) on other machines, too, and supporting intel-mpi and srun widen our options...

@uvaaland : can I ask you to check if specfm can easily be compiled with Intel-MPI?  I would then look into `srun` again.

**Comment by andre-merzky** [comment] 2019-04-30 11:16
The srun launch method is not implemented in radical-cybertools/radical.pilot/pull/1854

**Comment by uvaaland** [comment] 2019-04-30 14:05
I am currently recompiling using `intel-mpi/intel/2018.3/64` and rerunning the specfem mesher and solver to check that it works. Will report back once the results are in.

**Comment by uvaaland** [comment] 2019-05-01 10:08
I have successfully recompiled and run the specfem mesher and solver on `tigergpu` using the `intel/18.0` and `intel-mpi/intel/2018.3/64` modules.

**Comment by andre-merzky** [comment] 2019-05-01 10:11
Ah, cool - then let me switch the RP config to `intel-mpi`, and the mpirun problem should be solved, too!

**Comment by andre-merzky** [comment] 2019-05-01 12:26
This seems to work as expected, and is now configured in the `feature/tiger` branch of RP.  Would you mind giving this a try?  Thanks!

**Comment by uvaaland** [comment] 2019-05-01 18:57
Are you referring to the following steps?

```bash
$ git clone git@github.com:radical-cybertools/radical.pilot.git
$ cd radical.pilot
$ git checkout feature/tiger
$ ./bin/radical-pilot-ve ve
$ source ve/bin/activate
(ve) $ pip install .
(ve) $ ./bin/radical-pilot-create-static-ve ~/radical.pilot.sandbox/ve.princeton.tiger/
(ve) $ ./examples/09_mpi_units.py princeton.tiger_cpu
(ve) $ ./examples/09_mpi_units.py princeton.tiger_gpu
```

**Comment by vivek-bala** [comment] 2019-05-01 19:11
That sounds correct to me.

**Comment by andre-merzky** [comment] 2019-05-01 19:59
Yes!

**Comment by uvaaland** [comment] 2019-05-03 15:29
I have run the above steps again on Tiger and both examples run successfully.

**Comment by vivek-bala** [comment] 2019-05-03 15:37
Awesome!

**Comment by andre-merzky** [comment] 2019-05-03 15:38
Thanks!

**Comment by uvaaland** [comment] 2019-05-15 19:08
I am still seeing the same issue trying to run EnTK from my desktop machine. I did a fresh install of the feature/tiger branch, but the error is still the same: Resource allocation failing with the same complaint:

NoSuccess: Error finding SLURM tool squeue on remote server slurm://localhost/!

Then I tried running only the Pilot on Tigercpu from my desktop machine. I did so by following the steps:

$ git clone git@github.com:radical-cybertools/radical.pilot.git
$ cd radical.pilot
$ git checkout feature/tiger
$ ./bin/radical-pilot-ve ve
$ source ve/bin/activate
(ve) $ pip install .
(ve) $ ./bin/radical-pilot-create-static-ve ~/radical.pilot.sandbox/ve.princeton.tiger/
(ve) $ ./examples/09_mpi_units.py princeton.tiger_cpu

But modifying ./examples/09_mpi_units.py to use ssh as the schema in the resource allocation. Then I get an error:

caught Exception: prompted for unknown password (Password: ) (/home/uvaaland/scratch/tmp/radical.pilot/ve/lib/python2.7/site-packages/radical/saga/utils/pty_shell_factory.py +321 (_initialize_pty)  :  % match))

Though I have passwordless ssh set up from my desktop machine to Tiger, which I tested separately on the command line.

**Comment by uvaaland** [comment] 2019-05-15 19:58
Trying to run the example script again, I get a similar, but different message:

```bash
Permission denied (keyboard-interactive).
)) (/home/uvaaland/scratch/tmp/radical.pilot/ve/lib/python2.7/site-packages/radical/saga/utils/pty_exceptions.py +44 (translate_exception)  :  elif 'pass'                       in lmsg: e = se.AuthenticationFailed(cmsg))
Traceback (most recent call last):
  File "/home/uvaaland/scratch/tmp/radical.pilot/ve/lib/python2.7/site-packages/radical/saga/utils/pty_shell_factory.py", line 313, in _initialize_pty
    n, match = pty_shell.find (prompt_patterns, delay)
  File "/home/uvaaland/scratch/tmp/radical.pilot/ve/lib/python2.7/site-packages/radical/saga/utils/pty_process.py", line 796, in find
    raise ptye.translate_exception (e, "(%s)" % data)
AuthenticationFailed: read from process failed '[Errno 5] Input/output error' : (f the following options:

 1. Duo Push to XXX-XXX-3048
 2. Phone call to XXX-XXX-3048
 3. SMS passcodes to XXX-XXX-3048 (next code starts with: 1)
```

It is running into an issue with DUO, but this is interesting because it is not an issue if I `ssh` onto Tiger from the command line. That is, the following command:

```bash
ssh uvaaland@tigercpu.princeton.edu
```

works without prompting me for a password or DUO, but when I run the example in the same terminal window it fails with the DUO issue. The full `radical.saga.pty.log` file is attached.

[radical.saga.pty.log](https://github.com/radical-collaboration/hpc-workflows/files/3184220/radical.saga.pty.log)

**Comment by andre-merzky** [comment] 2019-05-15 20:02
Thanks Uno - can you please also set (if you don't have those yet)
```
export RADICAL_VERBOSE=DEBUG
```
and also attach a tarball with the session subdir and the logfiles therein?  Thanks.

**Comment by uvaaland** [comment] 2019-05-16 14:54
Great! I ran it again with the additional debug flag. Attached is the `radical.saga.pty.log` file and the RP session folder.

[issue.tar.gz](https://github.com/radical-collaboration/hpc-workflows/files/3187645/issue.tar.gz)

**Comment by uvaaland** [comment] 2019-05-16 15:12
Agreed. What I was telling Andre is that the connection works from the command line. No password, no DUO. But for some reason that is not the case when the pilot tries to do the same. I checked the resource file for Tiger and saw that it uses the same as I do from the command line (uvaaland@tigercpu.princeton.edu) and the user is always my Princeton username (uvaaland).

Andre was going to see if he could find the line that the Pilot uses to connect such that I could try and run the same line from the command line and check if that works.

**Comment by vivek-bala** [comment] 2019-05-16 15:22
I see, okay. I think Andre will be able to debug this. FWIW, the ssh command executed seems to be:
```
/usr/bin/env TERM=vt100 /usr/bin/ssh -t -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_uvaaland_%h_%p.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 tigercpu.princeton.edu
```

**Comment by vivek-bala** [comment] 2019-05-16 15:25
Taking a shot in the dark, can you try after adding the following to ```$HOME/.ssh/config``` (if you don't already have this):

```
Host tigercpu.princeton.edu princeton.tigercpu
    Hostname tigercpu.princeton.edu
    User uvaaland
```

**Comment by uvaaland** [comment] 2019-05-16 15:28
Yes, that is what I use, but had not set the user explicitly. I just set this and tried to run it again, but the error is the same. Should I try to run the above command from the command line?

**Comment by vivek-bala** [comment] 2019-05-16 15:31
Yea, I would say so. The 'User' is essentially your username on Tiger (```whoami``` on Tiger should confirm that). After adding the entry in .ssh/config file, I would suggest trying 
```
/usr/bin/env TERM=vt100 /usr/bin/ssh -t -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_uvaaland_%h_%p.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=10 tigercpu.princeton.edu
```
 one more time.

**Comment by vivek-bala** [comment] 2019-05-16 15:33
> So this is really a DUO issue.

Maybe some of the parameters are conflicting with the DUO settings? Let's see what Andre suggests.

**Comment by uvaaland** [comment] 2019-05-16 15:37
This is very interesting. Because when I run the same command a second time in the same terminal, it goes right through without a DUO issue. That is, if I run the above command from the command line and put in DUO, then I run the Pilot with the example script `./examples/09_mpi_units.py princeton.tiger_cpu`, it does not get stuck on DUO.

**Comment by uvaaland** [comment] 2019-05-16 15:40
I still don't see any jobs submitted on Tiger, but the Pilot reaches the `gather results` stage.

So circumventing DUO is something that I might just have to do by running the ssh command in the command line once before I try to launch an application with the Pilot. It is not a perfect solution, but something we can work with at least.

**Comment by vivek-bala** [comment] 2019-05-16 15:50
Yea, that sounds quite odd. Maybe there is a DUO timeout per session? You can keep the session persistent by using something like tmux: you can start a tmux session and setup DUO and continue using EnTK/RP in that session. You will be able to connect and disconnect with this session, checkout [this](https://www.hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/) for a quick how-to on tmux if required.

**Comment by uvaaland** [comment] 2019-05-16 15:55
Yes, I am using tmux. The way I have DUO configured is such that you require one DUO authentication per internet connection. That is, as long as my tmux session is open and the internet does not drop on my local desktop (which is very rare since it uses a cable), I should not have to deal with DUO again.

Now that we have found a way to get past this step, I don't expect it to be an issue, and I will focus on what else might be needed to get the pilot example to work when launching it from my desktop machine. Currently, it hangs at `gather results` and have done so for the past 15 minutes. I have also checked the queue on Tiger and have not seen any jobs being submitted.

**Comment by vivek-bala** [comment] 2019-05-16 15:58
> The way I have DUO configured is such that you require one DUO authentication per internet connection.
Is this based on your IP? RP underneath starts multiple ssh connections (3 I think). 

Anyway, good that this isn't an halting issue anymore.

**Comment by uvaaland** [comment] 2019-05-16 16:01
I am not sure. But it means that anytime I `ssh` from the same machine, I will not be prompted for DUO. So it should not be an issue that it opens up several ssh connections as long as DUO has been put in once.

**Comment by uvaaland** [comment] 2019-05-16 16:02
What is the best way to figure out what might be going on when I am stuck at `gather results`. Could I abort (`Ctrl+C`) and check the log files?

**Comment by uvaaland** [comment] 2019-05-16 16:04
I think the DUO issue is tied to the ControlPath being different in the command line command and my config file. On my system, I use ~/.ssh/sockets as my ControlPath, and that should be why there was a mismatch between me running `ssh` directly on the command line and the Pilot trying to do the same.

**Comment by vivek-bala** [comment] 2019-05-16 16:08
> What is the best way to figure out what might be going on when I am stuck at gather results. Could I abort (Ctrl+C) and check the log files?

Yes, you can Ctrl+C it. Give it about a minute as it might take some time. If it still doesn't abort after few minutes, you can Ctrl+Z and kill it (```$ kill %``` after Ctrl+Z). You should be able to whatever logs have already been created.

**Comment by vivek-bala** [comment] 2019-05-16 16:09
> I think the DUO issue is tied to the ControlPath being different in the command line command and my config file. On my system, I use ~/.ssh/sockets as my ControlPath, and that should be why there was a mismatch between me running ssh directly on the command line and the Pilot trying to do the same.

I see. Thanks for checking!

**Comment by uvaaland** [comment] 2019-05-29 16:17
The latest with this issue is that we have been able to work around the `ssh` issue when launching the pilot example `09_mpi_units.py` on Tigercpu, but it gets stuck at the `gather results` stage.

Checking the queue on Tigercpu shows that no jobs have been submitted, but several `ssh` connections have been made from the desktop machine onto Tigercpu. Since the session hangs and doesn't fail, I am not sure how to gather information on why it is getting stuck.

Let me know if you have any suggestions.

**Comment by andre-merzky** [comment] 2019-05-29 16:30
Please do interrupt with `CTRL-C` and attach the session sandboxes from the client and remote side.  Thank you!

**Comment by uvaaland** [comment] 2019-05-29 16:37
Attached are the session sandboxes from the client and remote side.

[session.tar.gz](https://github.com/radical-collaboration/hpc-workflows/files/3233506/session.tar.gz)

**Comment by andre-merzky** [comment] 2019-05-29 17:39
Hi Uno - that session seems to get terminated (by `CTRL-C`?) while the pilot is still being submitted - data staging seems to take a while?  20 min seems like a very long time...  Hmm.  I'll look into what is eating that time - meanwhile, can you please set `RADICAL_PROFILE=True` and run again, letting it run for some time longer (say, 40 min)?  

This by no means should be a normal runtime, but I would like to see what happens to the pilot...

Thanks!

**Comment by uvaaland** [comment] 2019-05-29 17:44
Yes, I will get right to it. As mentioned, once I launch the example from my desktop machine I can see 9 `ssh` connections to Tiger from my desktop, but no jobs are being submitted to the queue.

I will let the job run for at least 40 minutes and report back. Thanks!

**Comment by uvaaland** [comment] 2019-05-29 18:36
Session files for attempted run for ~50 minutes. The session still hangs at `gather results` and was interrupted with `CTRL-C`.

[session.tar.gz](https://github.com/radical-collaboration/hpc-workflows/files/3233927/session.tar.gz)

**Comment by andre-merzky** [comment] 2019-05-29 18:47
Thanks Uno - the behavior is the same, meaning that it hangs at the exact same log entry, when trying to submit the pilot to the batch system.  So it seems to me like the shared channel setup is successfully used for the data staging (the pilot data are staged completely into the pilot sandbox), but it seems insufficient to manage the channel used for the batch job submission.

I propose we try to set up an ssh tunnel and try to convince all RCT to use that one tunnel.  That would resolve both the problem of the DUO confirmation step, and should also not limit the number and type of channels opened.  I will try to document how to set this up.

**Comment by uvaaland** [comment] 2019-05-29 18:55
Great, that sounds like a plan!

**Comment by andre-merzky** [comment] 2019-06-03 06:32
It does, I think I have a mental image how we can get this to work.  It will not be a quick process unfortunately.  

How far are we away from you being able to run useful science *from the login node*?

**Comment by uvaaland** [comment] 2019-06-03 14:56
The current status on the head node is that we were able to successfully run the Pilot MPI examples. The reason why we put this approach on hold for a bit was the inconvenience of dealing with the RabbitMQ dependency that ENTK has.

Now, Vivek has pointed out the options to get around this on the head node and I can take some time this week to look at it. That way we can move forward with getting things to run on Tiger at the same time as the ssh tunnel solution is being developed.

**Comment by uvaaland** [comment] 2019-06-03 15:30
Successfully ran ENTK example `get_started.py` from the head node, using the VM option for the RabbitMQ dependency and with the `devel` branch of radical.pilot installed to pick up the `feature/tiger` commits.

That is, we have a successful run with ENTK on Tiger! 👍  I will document the required steps and then try an example run with SPECFEM on multiple CPUs and report back.

**Comment by andre-merzky** [comment] 2019-06-03 16:51
fantastic!  FWIW, tiger support will be part of tomorrows RP release....

**Comment by uvaaland** [comment] 2019-06-05 13:51
I have successfully run the SPECFEM mesher and solver through ENTK on Tiger with the Intel compilers. I have only run on CPUs, but this is enough to allow us to start playing with SPECFEM pipelines on Tiger. In other words, this is great news! 👍 

One question I have is with regards to the `radical.pilot.sandbox` folder. By default it ends up in `$HOME`, but we only have ~20GB of storage in this location on Tiger. I would like for this folder to be in `/scratch/gpfs/uvaaland` where I have ~500GB. Should I fix this with a symlink, or is there a straight forward way to define a different path for the Pilot/ENTK?

**Comment by andre-merzky** [comment] 2019-06-05 17:52
Hi Uno, 

that sounds great  :-D

The pilot sandbox root is specified [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_princeton.json#L32) - `radical.pilot.sandbox` is created under the path specified here.

**Comment by uvaaland** [comment] 2019-06-07 14:16
> fantastic! FWIW, tiger support will be part of tomorrows RP release....

Hi, Andre! I see the `princeton.tiger_cpu` resource is still not available in the `master` branch. I am currently putting together some documentation on how to run EnTK on Tiger and am wondering if I should put in instructions for how to install the `devel` branch of the pilot or if the merge is just around the corner such that I can work with the `master` branch instead?

**Comment by uvaaland** [comment] 2019-06-07 14:33
> Hi Uno,
> 
> that sounds great :-D
> 
> The pilot sandbox root is specified [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/configs/resource_princeton.json#L32) - `radical.pilot.sandbox` is created under the path specified here.

So if I want to set a different path on Tiger, say `/scratch/gpfs/uvaaland/`, then I should update lines 32 and 36 in the resource file to reflect that?

**Comment by mturilli** [comment] 2019-06-07 15:16
> So if I want to set a different path on Tiger, say /scratch/gpfs/uvaaland/, then I should update lines 32 and 36 in the resource file to reflect that?

Updating line 32 should be enough or do you need/want to change also the name of the VE used by RP?

**Comment by mturilli** [comment] 2019-06-07 15:17
Apologies, I see now what you meant. Yes, assuming you do not use in 32 then you would have also to edit 36

**Comment by lsawade** [comment] 2019-07-03 23:04
Hi!

I have been working with Unos example workflows to get specfem (and eventually my own workflow) running on the cluster here. While the CPU version seems to run smoothly, I have encountered some issues with the GPU queue.
I haven't been able to make a simple compiled GPU vector-add function without any inputs run.

One issue is usually that modules can't be found even though loading them in the terminal is not a problem.
`module purge` for example resulted in an error that the module to be purged couldn't be found, which I thought was strange.

The second issue I have encountered is that asking for resources for a specific task will result in an error.
So, below is the setup that I use for a simple Hello World example. As soon as I set the `t.gpu_reqs`, the code does not work anymore.

```python

# Task
t = Task()                                                                                                                                                                                                  
t.pre_exec= ['module load intel', 'module load intel-mpi', 'module load cudatoolkit']
t.name = 'my-first-task'        # Assign a name to the task (optional, do not use ',' or '_')
t.executable = '/bin/echo'   # Assign executable to the task
t.arguments = ['Hello GPU world'] # Assign arguments for the task executable
t.download_output_data = ['STDOUT', 'STDERR']
t.gpu_reqs = {'processes': 1,
              'process_type': None,
              'threads_per_process': 1,
              'thread_type': None
              }              

# Appmanager
res_dict = {'resource':  'princeton.tiger_gpu',
            'project' : 'geo',
            'queue'   : 'gpu',
            'schema'  : 'local',
            'walltime': 10,
            'cpus'    : 1,
            'gpus'    : 1
            }
```

I feel like I'm either missing something or doing something wrong. Another thing that I have noticed in the SLURM jobinfo that the pilot will ask for a full GPU node (28 CPUs and 4 GPUs) even though I only ask for 1 CPU. Is that supposed to happen?

Another issue I have encountered is the following, which appeared after running the pipeline a bunch of times:

```python
Traceback (most recent call last):
  File "get_started_head_node.py", line 71, in <module>
    appman.run()
  File "/home/lsawade/.miniconda3/envs/entk/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 310, in run
    self._resource_manager._submit_resource_request()
  File "/home/lsawade/.miniconda3/envs/entk/lib/python2.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 125, in _submit_resource_request
    self._session = rp.Session(dburl=self._mlab_url, uid=self._sid)
  File "/home/lsawade/.miniconda3/envs/entk/lib/python2.7/site-packages/radical/pilot/session.py", line 266, in __init__
    % (dburl, ex))  
RuntimeError: Couldn't create new session (database URL 'mongodb://user:user123@ds043012.mlab.com:43012/princeton' incorrect?): too many namespaces/collections
```

Thanks!

**Comment by shantenujha** [comment] 2019-07-10 01:01
Hi @andre-merzky @mturilli @lee212 --- gentle ping if you have any insight on what might be happening on Tiger?

**Comment by andre-merzky** [comment] 2019-07-10 10:28
Hey @lsawade, sorry for the late reply, but here are some answers I hope:

> One issue is usually that modules can't be found even though loading them in the terminal is not a problem. `module purge` for example resulted in an error that the module to be purged couldn't be found, which I thought was strange.

Indeed, that should not happen.  I don't see a `module purge` in the script you quoted, can you send what exactly you tried there so that I can try to reproduce it?  Thank you.  Do the `module load` commands you have above work like that, or do they also fail?

> The second issue I have encountered is that asking for resources for a specific task will result in an error.  So, below is the setup that I use for a simple Hello World example. As soon as I set the t.gpu_reqs, the code does not work anymore.

The req spec looks good to me, and that exact task spec seems to work for me (including the pre-execs).  I am using this stack on Tiger right now:
```
  python               : 2.7.5
  pythonpath           :
  virtualenv           : /scratch/gpfs/amerzky/radical/radical.pilot/ve

  radical.entk         : 0.7.17
  radical.pilot        : 0.62.0-v0.62.0-523-g79dbc2f@devel
  radical.saga         : 0.70.0
  radical.utils        : 0.70.0
```
So everything is installed from the released version - only `radical.pilot` is installed from the `devel` branch.

What is the version of RCT you are on?  You should find out with the command `radical-stack` - please paste the output.  Can you please create a tarball of the pilot sandbox and attach it to this issue?  Please make sure you have `RADICAL_LOG_LVL=VERBOSE` set in your environment, that will trigger our software to create detailed logfiles which help us understanding the issue.  Those logs should also help with the `module purge` problem, so please do include the unit sandbox in the tarball.

FWIW, the pilot sandbox should be under `/scratch/gpfs/<username>/radical.pilot.sandbox/<session_id>/pilot.0000/`.

> Another thing that I have noticed in the SLURM jobinfo that the pilot will ask for a full GPU node (28 CPUs and 4 GPUs) even though I only ask for 1 CPU. Is that supposed to happen?

Yes, we indeed allocate in general full compute nodes.  Most clusters we operate on do not support partial node allocation in the first place.  Does Tiger allow that, and is this a feature you need?  If yes to both,  we should be able to provide partial allocations.  But as said, our stack does not frequently run in that configuration, so we will have to do some testing to confirm that it handles that as expected.

> RuntimeError: Couldn't create new session (database URL 'mongodb://user:user123@ds043012.mlab.com:43012/princeton' incorrect?): too many namespaces/collections

This indicates that the MongoDB is configured to limit the number of collections per database, and that this number os reached.  You either have to manually purge the database, or increase the limit in the DB configuration, or use a different database (like `mongodb://user:user123@ds043012.mlab.com:43012/princeton_2`).

Unfortunately, mlab services seem to have deteriorated somewhat - we frequently did not manage to purge a database in the online interface.  If that happens to you, too, we would advise to switch to a different provide (although I don't have a good recommendation) or host a MongoDB on your own.  Let us know if you need further help on this item.

**Comment by lsawade** [comment] 2019-07-15 18:41
Hi @andre-merzky,

I got stuff to work. And resources were allocated correctly. 

I encountered a new error, which is not really an error per sé, but it worked before, so I thought it's worth a mention:
```python
port = os.environ.get('RMQ_PORT', 5672)
```
had to be changed to 
```python
port = int(os.environ.get('RMQ_PORT', 5672))
```
otherwise I got the error that the port has to be an integer. I am sure you were aware of that.

For future reference, what logs do I look at for debugging in general? I found some important info in the `bootstrap_0.{out,err}`. but not everything I would like to see, I think.

> Does Tiger allow that, and is this a feature you need? If yes to both, we should be able to provide partial allocations.

Tiger does allow that, and especially for quick debugging of small executions that would be helpful. At the moment, one run of the GPU pipeline just for the `echo` example takes approximately 2-3 minutes, just because I have to wait for the allocation of at least one full node.

Also, `mongodb://user:user123@ds043012.mlab.com:43012/princeton_2` did not respond or exist, but I figured out how to purge the MongoDB database, which was more tricky than expected.

**Comment by lsawade** [comment] 2019-07-15 20:14
> I encountered a new error, which is not really an error per sé, but it worked before, so I thought it's worth a mention:

 ```python
port = os.environ.get('RMQ_PORT', 5672)
```
had to be changed to
```python
port = int(os.environ.get('RMQ_PORT', 5672))
```

Just found in the docs, that that is the usual way...

**Comment by andre-merzky** [comment] 2019-07-19 16:58
> > Does Tiger allow that, and is this a feature you need? If yes to both, we should be able to provide partial allocations.
> 
> Tiger does allow that, and especially for quick debugging of small executions that would be helpful. At the moment, one run of the GPU pipeline just for the `echo` example takes approximately 2-3 minutes, just because I have to wait for the allocation of at least one full node

Point taken.  It's unlikely that we will support partial nodes quickly - it's simply not high enough on the priority list I'm afraid - but we'll keep it in mind on the next iteration of the resource allocator.

Re int casting for the port: We opened a ticket in EnTK to fix that, thanks!

**Comment by andre-merzky** [comment] 2019-07-19 16:59
PS.: if the stack is working on Tiger otherwise, feel free to close this specific issue and open new ones for each problem you find.

**Comment by lsawade** [comment] 2019-07-23 21:12
So, I'm still having issues with my pipeline, but I am not sure what the issue is as of now since I'm just waiting until the wall time has run out.
I have a feeling that the issue might be me requesting 2 GPU nodes which probably in total requests three nodes (the radical node plus the 2 requested ones, right?). 
Does it help if you cancel the computation and send you the tarball with the run info?

**Comment by mturilli** [comment] 2019-07-26 06:27
Hi @lsawade, I would open a new ticket:
- describing the issue you are encountering
- indicating the ID of the session that presented the issue (e.g., `rp.session.login1.mturilli1.018102.0001`)
- granting access to the session sandbox on Tiger (e.g., chmod 755 `radical.pilot.sandbox`)

In general, if you encounter an error and you execute a test, set the following environment variables:
```
export RADICAL_LOG_LVL="DEBUG"
export RADICAL_LOG_TGT="radical.log"
```
and make `radical.log` accessible as done with `radical.pilot.sandbox`

**Comment by lsawade** [comment] 2019-07-27 16:51
Hi @mturilli,

I'll open a new ticket. I think there might be an issue in the communication when trying to run stuff through the tigergpu queue. I'll attach all necessary files and give all write and read access to the necessary directories.

I think this issue can be closed for now as EnTK is running on the TigerCPU cluster successfully without issue!

**Comment by andre-merzky** [comment] 2019-07-29 11:05
Closing, discussion continues in #95.

**Closed by andre-merzky** 2019-07-29 11:05 UTC
Labels: Princeton, Rutgers, help wanted, priority:high
